library(pRycollection)
library(dataset)
data(package = "pRycollection")

head(py_temperature)
dim(py_temperature)
names(py_temperature)
print(py_temperature)
summary(py_temperature)
var_label(py_temperature$avg_temp)
var_unit(py_temperature$avg_temp)
attributes(py_temperature)
